redash:
  image: redash_oracle 
  ports:
    - "5000:5000"
  links:
    - redis
    - postgres
  environment:
    REDASH_STATIC_ASSETS_PATH: "../rd_ui/dist/"
    REDASH_LOG_LEVEL: "INFO"
    REDASH_REDIS_URL: "redis://redis:6379/0"
    REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
    REDASH_COOKIE_SECRET: veryverysecret
    REDASH_MAIL_SERVER: "smtp01.b2wdigital.com" # default: localhost
    REDASH_MAIL_DEFAULT_SENDER: "joao.leite@b2wdigital.com" # Email address to send from
redis:
  image: redis:2.8
postgres:
  image: postgres:9.3
  ports:
    - "5432:5432"
  volumes:
   - /opt/postgres-data:/var/lib/postgresql/data
redash-nginx:
  image: redash/nginx:latest
  ports:
    - "80:80"
  links:
    - redash
